version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"
  good-to-deploy:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Good To Deploy"
          command: "echo Good To Deploy!"

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
      - good-to-deploy:
          requires:
            - say-hello
